# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_delete_shelf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('status', models.IntegerField()),
                ('sname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aisle_shelf', to='storage.Aisle')),
            ],
        ),
    ]
