# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-17 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_shelf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('pcategory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='storage.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('tstart', models.DateField()),
                ('tend', models.DateField()),
                ('tcategory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_category', to='storage.Category')),
                ('tcustomer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='storage.Customer')),
                ('tshelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.Shelf')),
            ],
        ),
    ]
