# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-29 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_auto_20161221_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='birthday',
        ),
        migrations.AlterField(
            model_name='shelf',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
