# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-29 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0013_auto_20161229_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_category', to='storage.Category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tcustomer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.Customer'),
        ),
    ]
