# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-29 21:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0014_auto_20161229_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='end',
            field=models.DateField(blank=True, default=datetime.date(1999, 10, 31)),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='start',
            field=models.DateField(blank=True, default=datetime.date(1999, 10, 30)),
        ),
    ]
