# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-29 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0016_auto_20161230_0507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='tsatus',
            new_name='tstatus',
        ),
    ]
