# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-31 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0017_auto_20161230_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.IntegerField(default=10),
        ),
    ]
